server:
  port: 8085
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schema: classpath:db/scripts/jpa/create_tables.sql
    data: classpath:db/scripts/jpa/fill_tables.sql
    initialization-mode: never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
    generate-ddl: false
logging:
  level:
    org.springframework: ERROR
    com.kpi: DEBUG
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}) [%t] %clr(%-5level) %clr(%logger{36}){yellow} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: app.log
  logback:
    rollingpolicy:
      max-file-size: 200KB
