server:
  port: 8085
spring:

  # Oracle Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schema: classpath:db/scripts/oracleDB/jpa/create_tables.sql
    data: classpath:db/scripts/oracleDB/jpa/fill_tables.sql
    initialization-mode: never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
    generate-ddl: false
    database: default

  # MongoDB Configuration
  data:
    mongodb:
      uri: ${MONGO_DB_URL}

  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # Task Scheduling Configuration
  task:
    scheduling:
      pool:
        size: 3

  # Logging Configuration
logging:
  level:
    org.springframework: ERROR
    com.kpi: DEBUG
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}) [%t] %clr(%-5level) %clr(%logger{36}){yellow} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: app.log
  logback:
    rollingpolicy:
      max-file-size: 200KB
