server:
  port: 8085
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
logging:
  level:
    org.springframework: ERROR
    com.kpi: DEBUG
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}) [%t] %clr(%-5level) %clr(%logger{36}){yellow} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: app.log
  logback:
    rollingpolicy:
      max-file-size: 200KB
